name: Check changelog entries

on:
  pull_request:

jobs:
  check-changelogs:
    name: Check changelog entries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Check changelog entries
        run: uv run --no-sync python ci/check_changelog_entries.py
